### ISSUE TITLE
Support for more servers

### ISSUE THREAD

**Issue by qark** [ospaceteam/outerspace#11]
- Client should allow user to choose server
- Server should provide info text about its purpose and status [so it may be displayed within the choice dialog]

**Comment by dahaic** [comment]
Generally, if someone needs to run it's own server, it's either because of faster / different ticking, or because of changed technologies. It is not possible to do the latter unless #52 is implemented. Having support for metaservers just so they provide different ticking (and would have it's own registration, maintenance, possibly being out of date) is not worth the effort.

Closing this as won't fix.
