### ISSUE TITLE
 outerspace currently doesn't provide soft-core play

### ISSUE THREAD

**Issue by qark** [ospaceteam/outerspace#16]
With less people, players usually play with ~100 planets, which may be in case of war quite a time sink [in case you don't want to have poor effectivity]. 
With more people, galaxies ended after at least four months which is quite a lot as well.

**Comment by dahaic** [comment]
Galaxer now provides option of smaller 9-player galaxies. These are about 500 planets strong (mind you, this is counting all asteroid fields and gas giants, thus approx. half of them is available through the game). Another reduction of empire size is due to Mutant player expanding and colonizing through the galaxy, keeping portion of systems out of players reach. Will close this issue now.
