### ISSUE TITLE
Initial pause should provide planet production information and research points

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#213]
Right now, players waiting for the galaxy to start has no in game information how long it will take to build structures, or do a research. This is especially bad for new players, as they have no indication of building progression.

**Comment by temuchin-** [comment]
If you advance the entire turn by one, you would get these numbers. Seems the simplest way to get the results you want. Because the game always shows what current values are. This is why a new facility has no pop power or output assigned when it first comes into play. So the game working as intended.

Which means extend it by advancing the universe by 1, invoke the pause, then wait on the standard cron job task to issue new turns.

**Comment by dahaic** [comment]
Turn is advanced, as you said, for whole universe. That would mean every time there is new galaxy created, universe would tick one more time. So it wouldn't be suitable to implement it that way.

But there is actually precedent with handling of scanners - the scanner evaluation is triggered for the newly created galaxy, separately, out of normal turn procedure. So it's probably going to be simple change here as well.
