### ISSUE TITLE
better description of Circle9P galaxy

### ISSUE THREAD

**Issue by temuchin-** [ospaceteam/outerspace#231]
Line 193 +
  'Circle9P': N_("Smallest galaxy that contains full diplomacy rules set, limited strategic resources, and fully implements game mechanics. This galaxy is recommended for beginners who seek more casual gameplay with other like minded players."),

Line 193 -
  'Circle9P': N_("Smallest galaxy with Outer Space rules, recommended for beginners or those who seek more casual gameplay."),

/ Just a minor niggle that single player is currently smallest galaxy & learning rules in there works. so misleading text left over from 2010, maybe earlier?
// Next there is a need to dynamically display minimum num of players to start a galaxy. People who play are likely to be goal orientated. So w/ a goal on display they will be compelled to help reach said goal.

**Comment by dahaic** [comment]
As you have probably noticed, there are now multiple scenario types. Each scenario has slightly different ruleset, which in current iteration means difference in winning conditions. One of the scenario type is called `Outer Space` because it is the original one. And description of `Circle9P` is about this ruleset, not about the game itself.

For the minimum players - with smaller galaxies and different scenarios introduced, variable threshold for creation of galaxy has been removed, thus galaxy starts when all slots are filled in.

**Comment by dahaic** [comment]
Actually you are right, it's good to have your proposed description there.
